from libqtile import bar, widget
from libqtile.config import Screen
from libqtile.utils import ColorType
from colors import colors

screens = [
    Screen(bottom=bar.Bar([
        widget.Spacer(length=bar.STRETCH, background=colors["black"]),
        widget.GroupBox(foreground=colors["black"],
                        background=colors["black"],
                        font='Pixel Icons Compilation',
                        fontsize=25,
                        margin_y=3,
                        margin_x=10,
                        padding_y=5,
                        padding_x=20,
                        borderwidth=10,
                        active=colors["white"],
                        inactive=colors["white"],
                        rounded=True,
                        use_mouse_wheel = False,
                        highlight_method='block',
                        urgent_alert_method='block',
                        urgent_border=colors["emergency"],
                        this_current_screen_border=colors["primary"],
                        this_screen_border=colors["secondary"],
                        other_current_screen_border=colors["primary"],
                        other_screen_border=colors["secondary"],
                        disable_drag=True),
        widget.Spacer(length=bar.STRETCH, background=colors["black"]),
        widget.Systray(background=colors["black"],
                       foreground=colors["white"],
                       padding=15,
                       icon_size=21),
        widget.Spacer(length=15, background=colors["black"]),
        widget.Clock(background=colors["black"],
                     foreground=colors["white"],
                     format="%d/%m/%Y - %H:%M",
                     font="Mononoki Nerd Font",
                     fontsize=20,
                     padding=10),
        widget.Spacer(length=10, background=colors["black"]),
    ],
                          size=30,
                          opacity=0.95), ),
    Screen(bottom=bar.Bar([
        widget.GroupBox(foreground=colors["black"],
                        background=colors["black"],
                        font='Pixel Icons Compilation',
                        fontsize=25,
                        margin_y=3,
                        margin_x=10,
                        padding_y=5,
                        padding_x=20,
                        borderwidth=10,
                        active=colors["white"],
                        inactive=colors["white"],
                        rounded=True,
                        use_mouse_wheel = False,
                        highlight_method='block',
                        urgent_alert_method='block',
                        urgent_border=colors["emergency"],
                        this_current_screen_border=colors["primary"],
                        this_screen_border=colors["secondary"],
                        other_current_screen_border=colors["primary"],
                        other_screen_border=colors["secondary"],
                        disable_drag=True),
        widget.Spacer(length=bar.STRETCH, background=colors["black"]),
    ],
                          size=25,
                          opacity=0.95), ),
]